[package]
name = "cargo-lambda-metadata"
description = "Cargo subcommand to work with AWS Lambda"
version = "0.6.0"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/cargo-lambda/cargo-lambda"
repository = "https://github.com/cargo-lambda/cargo-lambda"
keywords = ["cargo", "subcommand", "aws", "lambda"]

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.
[dependencies]
cargo_metadata = "0.14.2"
miette = "4.3.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
