[workspace]
members = [
    "crates/cargo-lambda-build",
    "crates/cargo-lambda-cli",
    "crates/cargo-lambda-deploy",
    "crates/cargo-lambda-interactive",
    "crates/cargo-lambda-invoke",
    "crates/cargo-lambda-metadata",
    "crates/cargo-lambda-new",
    "crates/cargo-lambda-remote",
    "crates/cargo-lambda-watch",
]

exclude = [
    "test/fixtures/single-binary-package",
    "test/fixtures/mixed-workspace-package",
    "test/fixtures/missing-binary-package",
    "test/fixtures/multi-binary-package",
    "test/fixtures/target-dir-set-in-project",
    "test/fixtures/workspace-package",
    "test/integration/test-fun",
    "test/integration/test-ext",
    "test/integration/test-logs",
]

[workspace.package]
version = "0.11.3"
authors = ["David Calavera"]
edition = "2021"
license = "MIT"
homepage = "https://github.com/cargo-lambda/cargo-lambda"
repository = "https://github.com/cargo-lambda/cargo-lambda"
keywords = ["cargo", "subcommand", "aws", "lambda"]
description = "Cargo subcommand to work with AWS Lambda"
rust-version = "1.64.0"

[workspace.dependencies]
aws-config = "0.47.0"
aws-sdk-iam = "0.17.0"
aws-sdk-lambda = "0.17.0"
aws-sdk-s3 = "0.17.0"
aws-sdk-sts = "0.17.0"
aws-types = "0.47.0"
aws-smithy-types = "0.47.0"
cargo-lambda-build = { version = "0.11.2", path = "crates/cargo-lambda-build" }
cargo-lambda-deploy = { version = "0.11.2", path = "crates/cargo-lambda-deploy" }
cargo-lambda-interactive = { version = "0.11.2", path = "crates/cargo-lambda-interactive" }
cargo-lambda-invoke = { version = "0.11.2", path = "crates/cargo-lambda-invoke" }
cargo-lambda-metadata = { version = "0.11.2", path = "crates/cargo-lambda-metadata" }
cargo-lambda-new = { version = "0.11.2", path = "crates/cargo-lambda-new" }
cargo-lambda-remote = { version = "0.11.2", path = "crates/cargo-lambda-remote" }
cargo-lambda-watch = { version = "0.11.2", path = "crates/cargo-lambda-watch" }
clap = { version = "3.1.18", features = ["derive"] }
home = "0.5.3"
miette = { version = "4.7.1" }
reqwest = { version = "0.11.10", default-features = false, features = [
    "rustls-tls",
] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
strum = "0.24.0"
strum_macros = "0.24.0"
thiserror = "1.0.31"
tokio = { version = "1.18.2" }
tracing = { version = "0.1.35", features = ["log"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
uuid = { version = "1.1.2", features = ["v4"] }
which = "4.2.5"
zip = { version = "0.6.2", features = ["bzip2", "deflate", "time"] }

[profile.release]
strip = "symbols"
