[workspace]
members = [
    "crates/cargo-lambda-build",
    "crates/cargo-lambda-cli",
    "crates/cargo-lambda-deploy",
    "crates/cargo-lambda-interactive",
    "crates/cargo-lambda-invoke",
    "crates/cargo-lambda-metadata",
    "crates/cargo-lambda-new",
    "crates/cargo-lambda-remote",
    "crates/cargo-lambda-watch",
]

exclude = [
    "test/fixtures/single-binary-package",
    "test/fixtures/mixed-workspace-package",
    "test/fixtures/missing-binary-package",
    "test/fixtures/multi-binary-package",
    "test/fixtures/target-dir-set-in-project",
    "test/fixtures/workspace-package",
    "test/integration/test-fun",
    "test/integration/test-ext",
    "test/integration/test-logs",
]

[profile.release]
strip = "symbols"
