[workspace]
members = [
    "crates/cargo-lambda-build",
    "crates/cargo-lambda-cli",
    "crates/cargo-lambda-interactive",
    "crates/cargo-lambda-invoke",
    "crates/cargo-lambda-metadata",
    "crates/cargo-lambda-watch"
]

exclude = [
    "test/fixtures/single-binary-package",
    "test/fixtures/missing-binary-package",
    "test/fixtures/multi-binary-package",
    "test/fixtures/workspace-package"
]

[profile.release]
strip = "symbols"
