[package]
name = "cargo-lambda-invoke"
version = "0.1.0"
edition = "2021"
publish = false

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.
[dependencies]
clap = { version = "3.1.8", features = ["cargo", "derive"] }
home = "0.5.3"
miette = { version = "4.3.0", features = ["fancy"] }
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
