[package]
name = "cargo-lambda-watch"
version = "0.1.0"
edition = "2021"
publish = false

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.
[dependencies]
axum = "0.5.1"
cargo-lambda-interactive = { path = "../cargo-lambda-interactive" }
cargo-lambda-invoke = { path = "../cargo-lambda-invoke" }
cargo-lambda-metadata = { path = "../cargo-lambda-metadata" }
clap = { version = "3.1.8", features = ["cargo", "derive"] }
home = "0.5.3"
http-api-problem = { version = "0.51.0", features = ["api-error", "hyper"] }
miette = { version = "4.3.0", features = ["fancy"] }
opentelemetry = "0.17.0"
opentelemetry-aws = "0.5.0"
platforms = "2.0.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["sync", "time"] }
tokio-graceful-shutdown = "0.5.0"
tower-http = { version = "0.2.5", features = ["catch-panic", "request-id", "trace"] }
tracing = "0.1.32"
tracing-opentelemetry = "0.17.2"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
uuid = { version = "0.8.2", features = ["v4"] }
which = "4.2.4"
xz2 = "0.1.6"
zip = { version = "0.6.2", features = ["bzip2", "deflate", "time"] }
